# See: https://circleci.com/docs/2.0/configuration-reference
# See: https://circleci.com/docs/2.0/orb-intro/
# See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/ 
          # pip-dependency-file: test-requirements.txt 
      - run:
          name: Run Doctests
          command: |
            python src/rack.py
      - run:
          name: Run Tox py36 tests
          command: |
            tox -e py36
      - run:
          name: Run Tox py37 tests
          command: |
            tox -e py37
      - run:
          name: Run Tox py38 tests
          command: |
            tox -e py38
      - run:
          name: Run Coverage tests
          command: |
            coverage run --source=src setup.py test 
            coverage report -m

workflows:
  sample: 
    jobs:
      - build-and-test
